### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nucleartide** [headjump/pico8_html_template#1]
Hello,

This looks great! Is there a license for using the template?

**Comment by headjump** [comment]
You're right, I should include some kind of license. You can use it if you want, do with it what you like.
Could you suggest a license that basically says this?

**Comment by headjump** [comment]
I added License-Info to the readme (instead of adding a LICENSE.TXT, so there are no unnecessary files in the repo), but basically: use it how you like :)

**Comment by nucleartide** [comment]
Awesome, thanks! I'll let you know if I use it for a game. :)
