### ISSUE TITLE
iOS "Add to Home Screen" still have no sounds.

### ISSUE THREAD

**Issue by jasperdanan** [headjump/pico8_html_template#3]
After adding the PICO8 game to the Home Screen from Safari. The game still does not have sound.

Tested on:
2x iPhone 6 Plus - iOS 11.2.1
iPhone 6 - iOS 11.2.1
iPhone X - iOS 11.2

**Comment by nucleartide** [comment]
@jasperdanan To enable sound on iOS, check out https://github.com/nucleartide/fix-pico8-ios-sound.

**Comment by jasperdanan** [comment]
@nucleartide Thanks!

**Comment by jasperdanan** [comment]
Can confirm this fix works on all devices!
